#!/usr/bin/env bash
# shellcheck source=/dev/null

if [[ "${BASH_SOURCE[0]}" = "$0" ]];then
  # shellcheck disable=SC2016
  printf 'Error: `yabashlib` wrapper intended as a source, not an invokable script!\n' >&2
  exit 1
fi

for src in "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/src/*.sh; do
  source "$src"
done
